// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
//  await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTEhkyFDlUrb8IxzFQP2XvXQXdcRwQIU',
    appId: '1:311743340777:web:3dbb64b5d1c34322921078',
    messagingSenderId: '311743340777',
    projectId: 'thrive-ae59f',
    authDomain: 'thrive-ae59f.firebaseapp.com',
    storageBucket: 'thrive-ae59f.firebasestorage.app',
    measurementId: 'G-YR2BRZ774K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIGgdMQqQREudAYt3VI4PcFBRCrclIjtU',
    appId: '1:311743340777:android:4d2be9b4056864d7921078',
    messagingSenderId: '311743340777',
    projectId: 'thrive-ae59f',
    storageBucket: 'thrive-ae59f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOyCdiPKxH4qtISM2Sz4w-nLEzEWVxKUY',
    appId: '1:311743340777:ios:5902988b3e5a3399921078',
    messagingSenderId: '311743340777',
    projectId: 'thrive-ae59f',
    storageBucket: 'thrive-ae59f.firebasestorage.app',
    iosBundleId: 'com.example.thrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOyCdiPKxH4qtISM2Sz4w-nLEzEWVxKUY',
    appId: '1:311743340777:ios:5902988b3e5a3399921078',
    messagingSenderId: '311743340777',
    projectId: 'thrive-ae59f',
    storageBucket: 'thrive-ae59f.firebasestorage.app',
    iosBundleId: 'com.example.thrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDTEhkyFDlUrb8IxzFQP2XvXQXdcRwQIU',
    appId: '1:311743340777:web:47a15f315038f657921078',
    messagingSenderId: '311743340777',
    projectId: 'thrive-ae59f',
    authDomain: 'thrive-ae59f.firebaseapp.com',
    storageBucket: 'thrive-ae59f.firebasestorage.app',
    measurementId: 'G-Y26X1VLQEX',
  );

}